name: Build and Publish

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            libfido2_install: sudo apt-get update && sudo apt-get install -y libfido2-dev
            platform: linux
          - os: macos-latest
            libfido2_install: brew install libfido2
            platform: darwin
          - os: windows-latest
            libfido2_install: choco install -y libfido2
            platform: win32

    steps:
      - uses: actions/checkout@v4

      - name: Install libfido2
        run: ${{ matrix.libfido2_install }}
        shell: bash

      - name: Set LIBFIDO2_PATH on Windows
        if: matrix.os == 'windows-latest'
        run: echo "LIBFIDO2_PATH=C:\Program Files\libfido2" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Create lib directories
        run: mkdir -p binding/${{ matrix.platform }}-x64
        shell: bash

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create package
        run: npm run package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webauthn-node-${{ matrix.platform }}
          path: build/stage/*/*/*.tar.gz
          if-no-files-found: warn

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: find artifacts -type f

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.tar.gz
